# Generated by Django 3.2.8 on 2021-10-11 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('max_limit', models.FloatField()),
                ('risk_score', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Principals',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('investment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_type_ref', to='investment_app.investmenttype')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal_ref', to='investment_app.principals')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
