# Generated by Django 3.2.8 on 2021-11-07 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttype',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investmenttype',
            name='max_limit',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='investmenttype',
            name='risk_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='principals',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='principals',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
