# Generated by Django 3.2.8 on 2021-11-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0002_auto_20211107_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Principals',
            new_name='Principal',
        ),
        migrations.AddField(
            model_name='investment',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
