# Generated by Django 3.2.8 on 2021-11-07 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0005_transactional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trx_date', models.DateField()),
                ('buysell', models.CharField(choices=[('B', 'BUY'), ('S', 'SELL')], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=13)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_ref', to='investment_app.investment')),
            ],
            options={
                'ordering': ['-trx_date'],
            },
        ),
        migrations.DeleteModel(
            name='Transactional',
        ),
    ]
