# Generated by Django 3.2.8 on 2021-11-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0007_investmentbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentTypeBalance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('investment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bal_inv_type_ref', to='investment_app.investment')),
            ],
            options={
                'ordering': ['investment_type__name'],
            },
        ),
        migrations.DeleteModel(
            name='InvestmentBalance',
        ),
    ]
