# Generated by Django 3.2.8 on 2021-11-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0009_alter_investmenttypebalance_investment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttype',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
